  AllCops:
    NewCops: disable
    TargetRubyVersion: '2.6'

Gemspec/DateAssignment: # (new in 1.10)
  Enabled: true
Layout:
  Enabled: true
Lint:
  Enabled: true
Style:
  Enabled: true
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Enabled: false